### ISSUE TITLE
Memory release without allocation panic after "New blocks" commit 

### ISSUE THREAD

**Issue by morajabi** [yury/cidre#12]
I ran `cargo update` to use the latest commit. Suddenly this line of code caused a crash:
```
cidre::sc::ShareableContent::current().await;
```

without any stack trace but this error from my allocator (mimalloc): 

```
Memory released without being allocated first.
``` 
I downgraded to this commit: https://github.com/yury/cidre/commit/94c379f8b2eb1867bef314699fbed6d5a2f50df7
and issue was resolved. So I think the commit causing this is: https://github.com/yury/cidre/commit/2783e7b452590b6d1c79ef38adf87d88a00d1d0a

**Comment by yury** [comment]
Very good catch. I prepared fix. But I wan't to discuss default behavior.

I wan't to build `cidre` as performant as I could, so I assume objc and rust allocators are the same. Your use case unveiled another scenario, which is rare case in my opinion.

So I have two possible feature flags:

- `assume-system-allocator` - in this case user can opt-in optimizations on allocations/deallocations
- `custom-allocator` - in this case user can opt-in that he is using custom allocator

**Comment by morajabi** [comment]
Wow! 
So objc <> Rust inter-op would be faster if I use default allocator?

**Comment by morajabi** [comment]
I think default to optimizations and add `custom-allocator` flag.

**Comment by yury** [comment]
Feel free to reopen if needed
