### ISSUE TITLE
Add AVPlayerLayer

### ISSUE THREAD

**Issue by morajabi** [yury/cidre#15]
I'd like to show an AVPlayer in an NSView, seems like it needs an AVPlayerLayer. 

Also, I'd love to help you out with adding these, but I don't know what's the process of supporting a new type. Can you by any chance write a short guide on how you think it should be done?

**Comment by yury** [comment]
@morajabi  Here you go. You can use this commit as basic ref for adding new classes. But yet, I need to write some docs :)

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
