### ISSUE TITLE
Looking for AVAssetWriterInputPixelBufferAdapter support

### ISSUE THREAD

**Issue by clearlysid** [yury/cidre#16]
I'm trying to use this crate in my Rust app (thanks to @morajabi for the suggestion!)

Was looking for this class: https://developer.apple.com/documentation/avfoundation/avassetwriterinputpixelbufferadaptor

But I suppose it doesn't exist yet. How would one add it? I'm happy to spend some time creating a PR if any of the maintainers don't have time for it but can point me in the right direction.

**Comment by yury** [comment]
Sorry for delay, was moving to different apartment this weekend.

If you need another other missing api's feel free to request it or use this commit as ref.

**Comment by clearlysid** [comment]
No worries man! Congrats on the new apartment and thanks for the fab work!
