### ISSUE TITLE
Can I record audio using core_audio?

### ISSUE THREAD

**Issue by kusaanko** [yury/cidre#21]
I can't find `kAudioDevicePropertyStreamConfiguration` property in core_audio.
https://developer.apple.com/documentation/coreaudio/1545866-anonymous/kaudiodevicepropertystreamconfiguration
Do Core Audio implementations support audio recording?

**Comment by yury** [comment]
Hello, what kind of recording you would like?
I'm planning to implement AudioFile api today/tomorrow. Or you need different api?

PS: Added missing props.

**Comment by kusaanko** [comment]
Hi, I'm new to macOS API, so I don't know if this answers your question, but I want to use AudioUnit API.
https://developer.apple.com/documentation/audiotoolbox/audio_unit_v2_c_api
https://developer.apple.com/documentation/audiotoolbox/aurendercallbackstruct

**Comment by yury** [comment]
This [examples](https://github.com/yury/cidre/blob/2e76d334fed59d1393994a5042acdd64113ca7e3/cidre/src/at/audio/unit/output.rs#L273-L345) you want.

I will provide example app tomorrow

**Comment by yury** [comment]
They are actually basic tests. But I will provide example app to.

**Comment by kusaanko** [comment]
I want to use `kAudioDevicePropertyStreamFormat` property
https://developer.apple.com/documentation/coreaudio/1580731-anonymous/kaudiodevicepropertystreamformat
Could you add this?

**Comment by yury** [comment]
I really do not want to support deprecated API.
And that const is defined in `AudioHardwareDeprecated.h` header.

You can define it yourself:

```rust
const STREAM_FORMAT: AudioObjPropSelector = AudioObjPropSelector(u32::from_be_bytes(*b"sfmt"));
```

**Comment by kusaanko** [comment]
https://github.com/yury/cidre/blob/2e76d334fed59d1393994a5042acdd64113ca7e3/cidre/src/at/audio/unit/output.rs#L301-L310

Here I try to get the audio samples, but io_data.is_null() is true. So I got segmentation fault when I access to the raw pointer.
How to get samples? I'm waiting your example app.🙏

**Comment by yury** [comment]
[Here](https://github.com/yury/cidre/blob/main/cidre/examples/au-capture/main.rs) basic audio unit capture example. It is starting point, idea to show wave in ascii :)

**Comment by kusaanko** [comment]
Thank you! The example works on my device. Finally, I can record audio from mic!

I have a question.
There is a function `Output::set_current_device` for change the output current device, but there is no function for input.

I want to change the input device in order not to use the default device.
This code works, so that is no problem, but just wondering a little.

```rust
output.set_io_enabled(au::Scope::INPUT, 1, true)?;
output.set_io_enabled(au::Scope::OUTPUT, 0, false)?;

let property_address = core_audio::AudioObjPropAddr {
    selector: core_audio::AudioObjPropSelector::HARDWARE_DEVICES,
    scope: core_audio::AudioObjPropScope::GLOBAL,
    element: core_audio::AudioObjPropElement::MAIN,
};
let devices: Vec<core_audio::AudioObjId> = core_audio::AudioObjId::SYS_OBJECT
    .prop_vec(&property_address).unwrap();

let device_id = device[0]; // Select a device you want to use

output
    .unit_mut()
    .set_prop(
        au::PropId::OUTPUT_CURRENT_DEVICE,
        au::Scope::GLOBAL,
        au::Element(1),
        &device_id,
    );
```

**Comment by yury** [comment]
Ok, I fixed and tune some API.

Output unit property reports devices via `output_device` and `input_device`. 
Also added `core_audio::AudioObjId::SYS_OBJECT.hardware_devices()`  shortcut.
And proper implemented `input_stream_cfg` and `output_stream_cfg` for device.

Thank you for your patience and feedback.

**Comment by kusaanko** [comment]
Thank you for your effort!
I will close this issue.
Thank you so much.
