### ISSUE TITLE
Add screen capture kit example

### ISSUE THREAD

**Issue by thewh1teagle** [yury/cidre#23]
Hey!
Can you add screencapturekit example?
Previously I used [screencapturekit-rs](https://github.com/doom-fish/screencapturekit-rs) but it has memory issues so I want to try with this crate.

Thanks

**Comment by kusaanko** [comment]
https://github.com/yury/cidre/blob/main/cidre/examples/sc-record/main.rs
This code is what you want

**Comment by thewh1teagle** [comment]
Thanks! It looks a bit expressive. The crate intended to he direct bindings?
Also, is there a way to capture audio only?

**Comment by kusaanko** [comment]
The goal of this crate is to be able to use Apple SDK directly from Rust ( maybe ).
Basically, it is recommended to look up how to use ScreenCaptureKit in Swift as it can be written as is in Rust with Apple's documentation.
ScreenCaptureKit also supports audio-only recording, so of course it is possible!

Which data to use is specified here
https://github.com/yury/cidre/blob/a9e30a95f6e49d2f9aa1591900fd3a624bb20d01/cidre/examples/sc-record/main.rs#L386-L391

**Comment by kusaanko** [comment]
The code corresponds to this method
https://developer.apple.com/documentation/screencapturekit/scstream/3928168-addstreamoutput

**Comment by yury** [comment]
Closing?

**Comment by yury** [comment]
I'm closing this issue. Feel free to reopen if needed.

**Comment by thewh1teagle** [comment]
> ScreenCaptureKit also supports audio-only recording, so of course it is possible!
> 
> Which data to use is specified here

I tried to specify audio only just like you mentioned by adding audio only stream [here](https://github.com/RustAudio/cpal/pull/894/files#diff-579a20c2f694607c757fd91c0d2f9c7811f706b175b5d670a1317cb147b879feR202) but it still request permission for both audio&screen capture

<img src="https://github.com/user-attachments/assets/024f2550-7a63-404b-ac69-9d5fd6f2a10c" width=400>

I'm wondering if it's possible to request the system to record audio only just like it's listed here:

<img src="https://github.com/user-attachments/assets/4956d7a3-f670-4f5c-ac03-66240274731c" width=400>

**Comment by yury** [comment]
that is interesting, will try to investigate  tomorrow

**Comment by yury** [comment]
reworked all `core_audio` thing. Separate to  device types.

**Comment by yury** [comment]
Can't find a way to to specify only sys audio permissions for screen capture. So I provide another way to record system audio vide core_audio. See `core-audio-record` example.

**Comment by yury** [comment]
<img width="296" alt="Screenshot 2024-11-25 at 5 02 16 PM" src="https://github.com/user-attachments/assets/ef42d1eb-b537-4660-abc7-364b7b77e784">

**Comment by yury** [comment]
This example requires  only auto system recording access.
