### ISSUE TITLE
Is AVAudioFile available?

### ISSUE THREAD

**Issue by kusaanko** [yury/cidre#24]
I want to use `AVAudioFile` and `AVAudioPCMBuffer` in order to write aac file from raw pcm data, but I couldn't find them.
Are they available?
https://developer.apple.com/documentation/avfaudio/avaudiofile?language=objc

**Comment by yury** [comment]
I think, I'v implement all missing api... Please take a look.

**Comment by kusaanko** [comment]
How to create `av::audio::ChannelLayout`?

**Comment by kusaanko** [comment]
Awesome. Thanks!
