### ISSUE TITLE
Wrong encoding for cf::Url::with_path

### ISSUE THREAD

**Issue by kusaanko** [yury/cidre#25]
To convert from Rust's Path to URL, I used cf::Url::with_path.
But the generated string is used wrong encoding.
My macOS uses Japanese.

`MacBook Airのマイク` is converted to `MacBook Air縺ｮ繝槭う繧ｯ`

I changed https://github.com/yury/cidre/blob/b0be23bb78128365dc8fb155325ee962a0104efc/cidre/src/cf/url.rs#L65 to 
```Rust
cf::StringEncoding::UTF8
```
then the conversion succeeded.

My system returns `kCFStringEncodingMacJapanese = 1` from `StringEncoding::sys_encoding()`.

macOS uses UTF-8(NFD) as file names, so the conversion fails?

**Comment by yury** [comment]
Thank you!
