### ISSUE TITLE
Error building on macOS x86_64

### ISSUE THREAD

**Issue by morajabi** [yury/cidre#6]
Thanks for the awesome library!
I'm getting this error in my Github Actions build:
```
error: invalid register `x0`: unknown register
  --> /Users/runner/.cargo/git/checkouts/cidre-e660120dbd7e907a/2ecba7a/cidre/src/objc.rs:86:13
   |
86 |             lateout("x0") result,
```
Any idea how can I fix this/patch this?

**Comment by yury** [comment]
Thank you for your contribution. 

Just for me, for what are you planning to use cidre? And how you found it?

**Comment by morajabi** [comment]
@yury I wrote about it in this discussion a bit: https://github.com/yury/cidre/discussions/5
Happy to chat more! We use objc, objc2 and icrate in our app. I recently found `cidre` and love the focus on media capture and coding. Perfect for our current usecase for screenshare.

**Comment by yury** [comment]
@morajabi 
Oh, super cool. I don't know how I missed it :)

Btw [m1/m2 link](https://noor.to/download) here is 404.

**Comment by morajabi** [comment]
@yury Oh fixed! 
I've been working on getting cidre to compile on Intel thus the releases were a bit mixed up. I've got another issue and will make a PR for it soon. Do you think `cidre` should have a Github Action to check if it compiles after this?
